# Generated by Django 4.2 on 2023-06-11 06:56

import credential.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='face_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=250)),
                ('education', models.CharField(max_length=128)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('cpassword', models.CharField(max_length=128)),
                ('userphoto', models.ImageField(upload_to=credential.models.rename_userphoto)),
                ('cv', models.ImageField(upload_to=credential.models.rename_cv)),
            ],
        ),
    ]
